version: "3"

x-base-app: &base-app
  build: .
  volumes:
    - ../project:/var/www/laravel
  links:
    - postgres

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ../project:/var/www/laravel
      - ./nginx/:/etc/nginx/conf.d
    working_dir: /var/www/laravel
    links:
      - app
      - app_queue

  app:
    container_name: app
    <<: *base-app
    ports:
      - "9000:9000"

  app_queue:
    container_name: daemon
    <<: *base-app
    ports:
      - "8000:8000"
    entrypoint: ./daemon.sh

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lottery_db
    volumes:
      - ../project/tmp/db:/var/lib/postgresql
    ports:
      - 5432:5432